### PR TITLE
Add simple command-line interface

### PR DESCRIPTION
**Pull request by merwok**
For #42

### CODE REVIEW

**Comment by skorokithakis** [comment]
This needs more, for example using `argparse` to properly show the help text if the command is called with arguments, to show the version, etc. It also needs to be added to the `scripts` part of the setup.py so it gets properly installed as a command on installation.

**Comment by collinstocks-oscar** [comment]
If you're willing to pull in an external dependency, I've had good luck with https://github.com/google/python-fire for command-line interfaces.

**Comment by skorokithakis** [comment]
Unfortunately I think that's too heavy for a minor feature in this case.

**Comment by merwok** [comment]
In the initial feature request I was seeing this more as a bonus, like the easter eggs in the standard library (`python3 -m tarfile` or `python3 -m http.server`).  If you do want this as a standalone script with docs and all, I’ll have to spend more time on it :slightly_smiling_face: 

For command-line interface, given the Python versions supported by the project, argparse is not always available but really I would just use `len(sys.argv)` to see if we got 0, 1 (length) or 2 (length and number) params (inspiration from pwgen: https://linux.die.net/man/1/pwgen)

**Comment by skorokithakis** [comment]
Hmm, this is true, I guess argparse is 3.2+. I guess I'm just not a fan of having utilities that don't support at least `-h`, but if this is an easter egg that's undocumented and not to be relied upon, I guess this is fine.

**Pull request merged**
